baseURL = https://lims-uat.attunelive.net/ProductUI-Upgrade/Home.aspx
Username = Abiseik.prima.uat
Password = abc@12
Chromepath = ./Drivers//chromedriver.exe
OrgName = Prima Diagnostics
------------------------------------------------Roles,Location-----------------------------------------------------------------
Role1 = LabReception
Role2 = Administrator
Role3 = 
Role4 = 
Role5 = 
Role6 = 
Location1 = Jayanagar
Location2 = RR Nagar
--------------------------------------TestDetails-----------------------------------------------------------------------------
Salutation = Mr.
Email = dummy@gmail.com
Refdr = Self
Test1 = PBC0052
Test2 = PBC0040
Test3 = THYROID PROFILE
----------------------------------StatusDetails----------------------------------------------------------------------------------
Status = Received
Status1 = Not given
Status2 = Rejected
Status3 = OutSource
Status4 = Collected
ReasonforNotgiven = Patient Delay
ReasonforReject = Clotted sample
Status5 = Rerun
Status6 = Recollect
---------------------------------------RolesDetails-----------------------------------------------------------------------------
postion = Phlebotomist
postion1 = Lab Technician
postion2 = DEO B2B
postion3 = Pathologist
postion4 = Accession
postion5 = LabReception
postion6 = Administrator
position7 = SrLabTech
position8 = Center Manager
position9 = Credit Controller
Action = Collect Sample
Action1= Send Outsource Details
Action2= Capture OutSourcing Details
value = 3
Value1 = 4.5
-------------------------------------------ClientMasterDetails----------------------------------------------------------------
cctype= Collection Centers
cname= My Auto client 6
ccode= MAC6
btype= LAB
invoicecycle= 1 Day
addresstype= Bill To
address= Dummy Address
city= chennai
mobile= 9790981125
invoiceemail= dinakaran.g@attunelive.com
ctype= CLIENT
clname= Gokul

Clientcode = TC1
ClientName = Testing credit
Bussinesstype = HOSPITAL
InvoiceType = Orginal
InvoiceType2 = Draft

ClientBulk = Bulk Invoice
Bulkcode = BLK1

SelectAction = View Invoice
SelectAction2 = Show PDF
---------------------------------------------------CancelandRefund----------------------------------------------------
Dropdown = Cancel Bill

--------------------------------------------------Discount---------------------------------------------------------------
Discount = 10% - DISCOUNT - 10.00
Reason = Doctor recommendation
AuthrizedBy = Admin
Remarks = Testing
DateRange = Today
-----------------------------------------------OrgtoOrg-------------------------------------------------------------
OrgName = Prima whitefield
OrgLocation = whitefield
TransferOrgName = Prima whitefield(whitefield)
-------------------------------------------------ClientRateMappingDetails-----------------------------------------------------
Rtype= Normal
ratecard= GENERAL
DD= 31
MM= December,
YY= 2026
-------------------------------------------------NewGroupDetails--------------------------------------------------------------
Groupname=AutoGp 11
Groupcode=AGp11
Content1=PBC0045
Content2=PBC0052
Content3=PBC0040
SubGroup=PGRPB067
-------------------------------------------------OutsourceTest--------------------------------------------------------------------
OutsourceTest= PBC0045
--------------------------------------------------PackageDetails------------------------------------------------------------------
Packagename=Automation Pkg1
Billingname=Automation Pkg1
Packagecode=AP1
packagecontent1=Complete blood Count
packagecontent2=LIPID PROFILE
packagecontent3=LFT
packagecontent4=PBC0045
packagecontent5=PBC0052
packagecontent6=PBC0040
-----------------------------------------------TestMaster-----------------------------------------------------------------------
invname= Auto class 28
invcode= Ac28

invtype= Investigation

Department = CLINICAL BIOCHEMISTRY
DepartmentHeader = BIO CHEMISTRY
Sample = Blood
Additive = Sterile container
ResultValue = Alpha Numeric
Rangetype = Reference Range
Gender = Both
Category = Common
Valuetype = Between
Value1 = 1
Value2 = 30
Value3 = 3
Updation = TestMaster Updation

-------------------------------------------ManageUser-------------------------------------------------------------------------------
UserName = BatchRunG
EmpID = Batch7
Email = AutoNewuser@mail.com
Address1 = Automation1
City = Chennai
MobileNum = 9234561227
Newpassword = abc@12
-------------------------------------EditPatientDemography------------------------------------------------------
Editpatient1 = Edit Patient Registration Details
Editpatient2 = Mrs.
Editpatient3 = Edited Patient

RegistrationDate = Today
AutoTest1 = PBC0052
AutoTest3 = PBC0040
--------------------------------------Differentpaymentmodes-----------------------------------------------------
PaymentType1 = OnlinePayment
PaymentType2 = Credit/Debit Card
PaymentType3 = Credit Note
PaymentType4 = UPI Payments

CardType1 = Debit
CardType2 = CreditNote
CardType3 = UPI
CardNumber1 = 789564738292
CardNumber2 = 789564738283
CardNumber3 = 789564738274
AccountHolderName = Dummy
